name: Deploy React CICD to github

on:
  push:
      branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
        # Checkout the code
          - name: Checkout code
            uses: actions/checkout@v3

        # Setup Node the code
          - name: Setup Nodejs
            uses: actions/setup-node@v3
            with: 
              node-version: 18

        # Install  deps
          - name: Install Dependencies
            run: npm install 
        
         # Build Project  
          - name: Build project
            run: npm run build

         # Deploy APP in github pages 
          - name: Deploy to github pages
            uses: peaceiris/actions-gh-pages@v3
            with: 
              github_token: ${{secrets.GITHUB_TOKEN}}
              publish_dir: dist